language: node_js
node_js:
- 10
cache: npm
before_script:
- npm install
- npm install --no-save semantic-release @semantic-release/git @semantic-release/npm
  @semantic-release/changelog
script:
- npm run lint
before_deploy:
- npm run build-iife
- npm run build-es
- node .scripts/prepublish
- ls dist
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: I1y8Tf2A8K7vjUPIXCK+UCD9h3PTKFx5va9ZhQVuNMDCuuGdJZey2QKYy3ZZ2S15bZ+fDT9KG6ZDC7wyzm/EB7jGUFDNF3z4HrYYYB7cOQyn85tVzkb3ph2i8y8JZKgGncawQHy+8GEuPD6kxtXM8rx5A+XdOMfGTUXuP3k8BBGV8DF0tOPeKOKHTQ2bqJRIICLR4Yz4aPd9io54tkwlhz58oiOj6T4+b56EvljKTgsDkk6Ob6t0qgJBKS63Jq3uRMLcuTO4DwxhRBzcEPp+hAdIhmJemsdg82Q6UdJqLEyZ7ABydAOPxmWw/QbHoe/mJnTnzZ+4RdV9dDxEIHt71z6yyVlu8gJGsqBBW2vMQF1cFI3wCu1nnvwAJiF3FeQuIiTndtA31iWqCvXP4TA8j/SwDGAGUbjf61kEr51OFIHqNbvJc1oJQNt2Ekx6wpfbottDLGVA7sOWP9+AS4Kt73v2zoZ3FPDv9fWNOLc3psr8ofubXfWWxYiFGpQAnkbaEfULrQkNQkf2bQw3DIYl4OHkSEaGrcbM/Bn54EFGBRTe7oRC6MwEa++b1dAdumCQYwN0whQUrsTXircqbCzicy3fkyHb3cNo2gd9J/LHFicn0lCWzY1V8fXUakNzbZ9vtqaxGHincMY6Xwm03PE4pw5gZ4vtpKrTcNY1lmn/b8A=
  - secure: m1wM9jO/kuxnZnQapC22bnHySMx6RPb4StqTgFm/8CZ+StN9GtDKGtmIDnvRl2sT02+freGVAB9G4R6DvFbDstTcDEfJZ7UmmNRjwDaGsw1hnvO4JoyTs3ncK3/yR+7hFT1qVYs775sa8dhv/+ewgMpVv/rcG8OGCQibmkwxjOX+GsOr5og+qWvM8avwmN+ZUgO9bQMMsFHAIG3RdSPupmXq9A0hekUljSbtUL+lPl6gnY5+NbA7KO/KyVWEueHrSyBZXYlnY1nqMRmHVNGowQVy4G1Rq84b/GGnOzydW1lNEa7D3A7OqCWmHd81WA81+puDMr6BuxZPl0KluOvwVRBS4s+ghV2+4XPE5YhZtKsE6J7MOjfwcv3d4Cdt6zcARgLRcd0OIBEp+3FBbdlSgIJMks0ipD6pbCGn2hOruxCD9n9wpv9Qi1Sp9Wcm9oYmrEyPNSAV7lfoWgxMxt4QSB5zQH/m79QXK5l4xX3H9U7x1Wr9ez+cZ3ac2/GBhPFmQIE9CL55plDEBl6OSOM7Xf/PTU7bHj99KV5LqXTHt/9pG5LWObne3aWfXsLX0vQmyspeawqOklcuI27BUoJ9XPpyAeH7gmfpvNq1Ft8wTrE1MSVVpW1SnKduWs1AKhDWsvNDO5mDkeGaRT405krUQg3xp693QILaltI+liuGkUU=
